let forumlist = [
  'New Scratchers',
  'Announcements',
  'Requests',
  'Show and Tell',
  'Collaboration',
  'Help with Scripts',
  'Project Ideas',
  'Bugs and Glitches',
  'Other Languages',
  'Questions about Scratch',
  "Things I'm Making and Creating",
  'Advanced Topics',
  "Things I'm Reading and Playing",
  'Suggestions',
  'Open Source Projects',
  'Connecting to the Physical World',
  'Developing Scratch Extensions',
  'Africa',
  'Bahasa Indonesia',
  'Català',
  'Deutsch',
  'Ελληνικά',
  'Español',
  'فارسی',
  'Français',
  'עברית',
  '한국어',
  'Italiano',
  'Nederlands',
  '日本語',
  'Norsk',
  'Polski',
  'Português',
  'Pусский',
  'Türkçe',
  '中文',
  'Translating Scratch'
];
export default forumlist;
